### PR TITLE
Updating static content

### PR DESCRIPTION
**Pull request by athai**

### CODE REVIEW

**Comment by athai** [comment]
Alongside the trivial grammar corrections, here the other differences/issues I found between the static and drupal sites:

**Organization/Staff**
* Lance's email is spelled out in his staff description i.e. lance-at-osuosl-dot-org (is that intentional?)
* github accounts aren't being linked to on the static site

**Organization/Researchers**
* Eric Walkingshaw's picture is the same as Alex Groce's on the static site? I don't think he as a picture listed in the images directory either. Should this just be left blank?
* Carlos' description seems to switch point of view midway through the 2nd paragraph

**Students**
* The static site is missing Ryan Ramey under students
* Again, github accounts are listed but not linked to

**Alumni**
* Should this section be updated?
* Chance's github account has been removed from his desc. on the static site

**Projects**
* The hierarchy seen on http://cass.oregonstate.edu/projects is not apparent on the static site. Can this not be done in rst?

What's important enough to warrant changing?

**Comment by matthewrsj** [comment]
* Lance's email is intentional so it doesn't show up as a mailto link.
* The github accounts did not used to be links on drupal, if that has changed, it is since that was written
* Eric Walkingshaw's picture... I don't know. Probably just blank.
* If Carlos's description wasn't written by Carlos, go ahead and fix it. I think I might have written that one.
* Remove Chance's github like on the drupal site, everything should look like the github site except for where it is obviously out of date
* /projects - The pelican site should look as close as possible to the drupal site if possible. You may have to experiment with rst to see if the structure is possible.

**Comment by lucywyman** [comment]
**Organization/Staff**
    *Lance's email is spelled out in his staff description i.e. lance-at-osuosl-dot-org (is that intentional?)*  
Yep! It's so bots can't read it.
    *github accounts aren't being linked to on the static site* 
That's cause drupal is dumb and I was too lazy to figure out how to get PHP to turn them into links-- they should be linked.

**Organization/Researchers**
    *Eric Walkingshaw's picture is the same as Alex Groce's on the static site? I don't think he as a picture listed in the images directory either. Should this just be left blank?*
Mmmm, yeah, probably.

**Organization/Students**
    *Again, github accounts are listed but not linked to*
They should be linked :/

**Organization/Alumni**
    *Should this section be updated?*
Yeah -- that's actually a project I'm working on now. I wouldn't let that hold us up from publishing the site -- it's just on the todo list.
    *Chance's github account has been removed from his desc. on the static site*
Oh, umm...I think we can add it. I don't see a reason why not.

**Organization/Projects**
*The hierarchy seen on http://cass.oregonstate.edu/projects is not apparent on the static site. Can this not be done in rst?*
This is one for Matthew :/

**Comment by matthewrsj** [comment]
I defer all these to @lucywyman. She did a much better job answering them.

**Comment by athai** [comment]
The projects page currently looks like this: http://i.imgur.com/aX9QtXn.png
I'm not sure how to manipulate further.

Also, should I readd Ryan Ramey to the list of students?

**Comment by lucywyman** [comment]
@athai I think the page looks great -- personally, I don't think it's a big deal that it looks a little different as long as the content is accurate. 

Ryan Ramey: Probably, as it seems like he just started so probably (hopefully) still works at CASS.

Do you mean the social media links? I think those all go to OSL social media. It's kind of on purpose? It's because they use the same theme, and I probably either hardcoded those into the theme or added the same links to the config file. Either way, I don't think CASS has things like a twitter or facebook, so for now at least I Wouldn't worry about it. It might be something that needs to be changed in the future, though.

**Comment by athai** [comment]
@lucywyman This is what I mean: http://i.imgur.com/8bFEVgo.png
The drupal site lists the OSL, SDG, Test Lab, and IoT on the side rather than CASS, EECS, and donate.

**Comment by lucywyman** [comment]
Ohh, I see. Umm...I honestly don't recall why I chose to do that instead of what's on the drupal site.  Maybe ask Ken which is better?

**Comment by Kennric** [comment]
@athai I am actually not sure myself. I would make sure all the written content (stories, descriptions, etc) are up to date, and then have Lance, Carlos, and Lydia look over the staging site to ok these differences in the menus and sidebars.

**Comment by athai** [comment]
Actually, Matthew said that the menus and sidebars were changed so that the theme can be as generalized as possible.

**Comment by Kennric** [comment]
+1

**Pull request merged**
