### PR TITLE
Added required metadata for generalized menu

### PR DESCRIPTION
**Pull request by matthewrsj**
Blocked by https://github.com/osuosl/dougfir-pelican-theme/pull/22

UNBLOCKED

### CODE REVIEW

**Comment by Kennric** [comment]
I don't see any problems, +1

**Comment by matthewrsj** [comment]
@ramereth

**Comment by ramereth** [comment]
Will this script be used with both sites eventually? Would it make sense to move it to the theme so that its centrally managed?

**Comment by matthewrsj** [comment]
Yes it will be used by both sites. I can put it in the theme if you want.

**Comment by Kennric** [comment]
Looks good - filter location is good, menu info looks correct. +1

**Pull request merged**
